Added a random texture change every 20 actions and added an option to decide how images are saved
anthonyjclark/boxnav pull request #13
Opened 2023-07-18 18:09 UTC by Framor81

2023-07-18 18:10 UTC, anthonyjclark requested changes

2023-07-18 18:10 UTC, anthonyjclark commented on box/boxunreal.py
> +            f"{self.images_saved:06}_{str(action).lower()}.{str(self.image_ext).lower()}"
I'd like the filename to use the angle to the target instead of the action name.

2023-07-18 20:39 UTC, Framor81 commented
Changed filename to degree instead of label.

2023-07-19 02:33 UTC, anthonyjclark approved these changes

2023-07-19 02:33 UTC, merged